# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
update_fastlane

default_platform(:ios)

platform :ios do
  desc "Build QA"
  lane :qa do
    match_qa
    build_qa
  end

  desc "Match QA"
  private_lane :match_qa do
    sync_code_signing(
      type: "adhoc",
      readonly: true,
      clone_branch_directly: true)
  end

  desc "Build IPA"
  private_lane :build_qa do
    build_app(
      workspace: "iOSBase.xcworkspace",
      scheme: "QA",
      export_method: "ad-hoc",
      configuration: "QA")
  end

  desc "Swiftlint"
  lane :swiftlint do
    swiftlint(
      reporter: "xcode",
      quiet: true,
      raise_if_swiftlint_error: true
    )
  end

  desc "Precheck"
  lane :dev_lane do
    build_app(
      workspace: "iOSBase.xcworkspace",
      scheme: "Develoment",
      skip_package_ipa: true,
      skip_archive: true,
      skip_codesigning: true,
      analyze_build_time: true,
      derived_data_path: "./DerivedData",
      clean: false,
      export_method: "development")
  end
end
