name: Build-QA

on:
  pull_request:
    branches: [ staging ]
    types: [closed]

jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: Trigger GitHub
        if: github.event.pull_request.merged == true
        env:
          JENKINS_TOKEN: ${{ secrets.JENKINS_TOKEN }}
        run: |
          curl \
          --insecure \
          --user namnh92:$JENKINS_TOKEN \
          --header "Content-Type: application/x-www-form-urlendcoded" \
          --request POST \
          --url https://jenkins.code4fun.group/job/Base/view/iOS/job/QA/job/iOS-QA-Diawi/buildWithParameters

